## Interview Preparation for NumPy

#### What is NumPy?

##### NumPy is a Python library used for working with arrays.

In [20]:
%pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 23.2.1 -> 23.3.2
[notice] To update, run: python.exe -m pip install --upgrade pip


#### List vs NumPy

1. NumPy arrays are stored at one continuous place in memory unlike lists, so processes can access and manipulate them very efficiently so, numpy array is very fast as compared to lists.
2. Numpy arrays have a fixed data type, meaning all elements must be of the same type. This leads to better performance and memory efficiency. In contrast, Python lists can contain elements of different data types.
3. numpy array have extra functionality than lists
4.  NumPy supports broadcasting, which is a powerful mechanism that allows NumPy to work with arrays of different shapes and sizes during arithmetic operations. 


        import numpy as np

        arr1 = np.array([1, 2, 3])
        arr2 = np.array([4, 5, 6])

        result = arr1 + arr2  # NumPy automatically broadcasts the addition

        print(result)
        
        Output: [5, 7, 9]



### Working with arrays

#### Ways of creating array in NumPy

In [21]:
import numpy as np

#1
arr = np.array([1,2,3,4,5,6])
print(arr)

#2 
arr1 = np.linspace(0,15,3)
#linspace(start,end(included),parts) by default parts are 50 if not mentioned and type of array will be float
print(arr1)

#3
arr2 = np.arange(1,21,4)
# arange(start,end(excluded),steps)
print(arr2)

#4
arr3 = np.logspace(1,40,5)
# logspace(start,end,parts)
# start from log 10 base 1,to log 10 base 40 and broken into 5 parts
print(arr3)

#5
arr4 = np.zeros(5) #---- float
arr5 = np.zeros(5,int) #----- int
print(arr4)
print(arr5)

#6
arr6 = np.ones(5,int)
print(arr6)
print()
arr7 = np.array([[[1,2,4],[2,3,4]],[[3,4,5],[6,5,4]]])
print(arr7)


[1 2 3 4 5 6]
[ 0.   7.5 15. ]
[ 1  5  9 13 17]
[1.00000000e+01 5.62341325e+10 3.16227766e+20 1.77827941e+30
 1.00000000e+40]
[0. 0. 0. 0. 0.]
[0 0 0 0 0]
[1 1 1 1 1]

[[[1 2 4]
  [2 3 4]]

 [[3 4 5]
  [6 5 4]]]


#### Operations on arrays

In [22]:
#--- Get Dimenshion
print(arr7.ndim)
print(arr5.ndim)

#--- Get Shape
print(arr7.shape)
print(arr6.shape)

#--- Get Type
print(arr4.dtype)
print(arr7.dtype)

#--- Accessing and changing specific elements in array(row,columns,etc)
print(arr7[1,1,2])

#--- Slicing (start,end(exclusive),step)
print(arr2[1:2:1])

print("-------------------")
#---reshape
print(arr,arr.reshape(1,6))

#--- Copying an array
# use copy keyword else original array will be changed also
print(arr1)
b = arr1
c = arr1.copy()
b[2] = 29
print(c)
print(arr1)


#--- join
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

print("=======================")
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=0)
print(np.concatenate((arr1,arr2),axis=1))
print(arr)
print("++++++++++++++++++++")
#--- array_split()  
'''We use array_split() for splitting arrays, we pass it the array we want to split and the number of splits.'''  
'''If the array has less elements than required, it will adjust from the end accordingly.'''          
print(np.array_split(arr,6))

#--- Array Search
'''You can search an array for a certain value, and return the indexes that get a match.

To search an array, use the where() method.'''
arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)
y = np.where(arr == 5)

print(x,y)

#--- Search Sorted()
'''There is a method called searchsorted() which performs a binary search in the array,
 and returns the index where the specified value would be inserted to maintain the search order.'''
### assumed to be used on sorted arrays

print(np.searchsorted(np.array([1,2,5,7,9]),4))

#--- sort()
''' It returns copy of the original array
If you use the sort() method on a 2-D array, both arrays will be sorted:'''
print(np.sort(np.array([11,43,5,6,88])))
print(np.sort(np.array([11,3,4,55,6,0,-5,9,-32]).reshape(3,3)))



3
1
(2, 2, 3)
(5,)
float64
int32
4
[5]
-------------------
[1 2 3 4 5 6] [[1 2 3 4 5 6]]
[ 0.   7.5 15. ]
[ 0.   7.5 15. ]
[ 0.   7.5 29. ]
[1 2 3 4 5 6]
[[1 2 5 6]
 [3 4 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
++++++++++++++++++++
[array([[1, 2]]), array([[3, 4]]), array([[5, 6]]), array([[7, 8]]), array([], shape=(0, 2), dtype=int32), array([], shape=(0, 2), dtype=int32)]
(array([3, 5, 6], dtype=int64),) (array([4], dtype=int64),)
2
[ 5  6 11 43 88]
[[  3   4  11]
 [  0   6  55]
 [-32  -5   9]]


In [23]:
import copy

In [24]:
check = [[1,2,3],[4,5,6]]
b = copy.copy(check)
# b[0] = [6,7,5]
print(b,check)
b[0][1] = 22
print(b,check)
print(id(b),id(check))

[[1, 2, 3], [4, 5, 6]] [[1, 2, 3], [4, 5, 6]]
[[1, 22, 3], [4, 5, 6]] [[1, 22, 3], [4, 5, 6]]
2171376215744 2171376220160
